name: Build and upload Python package

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Ensure version consistency
        run: |
          VERSION_SETUP=$(grep -oP '(?<=version=\").*(?=\")' setup.py)
          VERSION_KNOWLEDGE=$(grep -oP '(?<=__version__ = \").*(?=\")' knowledge_storm/__init__.py)
          VERSION_TINO=$(grep -oP '(?<=__version__ = \").*(?=\")' src/tino_storm/__init__.py)
          VERSION_PYPROJECT=$(grep -oP '(?<=version = \").*(?=\")' pyproject.toml)
          echo "Version in setup.py: $VERSION_SETUP"
          echo "Version in knowledge_storm/__init__.py: $VERSION_KNOWLEDGE"
          echo "Version in src/tino_storm/__init__.py: $VERSION_TINO"
          echo "Version in pyproject.toml: $VERSION_PYPROJECT"
          if [ "$VERSION_SETUP" != "$VERSION_KNOWLEDGE" ] || \
             [ "$VERSION_SETUP" != "$VERSION_TINO" ] || \
             [ "$VERSION_SETUP" != "$VERSION_PYPROJECT" ]; then
            echo "Error: Version mismatch detected"
            exit 1
          fi
        shell: bash
      - name: Install dependencies
        run: python3 -m pip install setuptools wheel twine
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build a binary wheel
        run: python3 setup.py sdist bdist_wheel
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
